config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :payments, controller: 'products/payments', only: %i[new] do
      collection do
        post 'order_intent' => 'products/payments#order_intent'
        post 'order_paypal' => 'products/payments#order_paypal'
      end
    end
  end

  get 'webhooks/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :payments, only: %i[create new] do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  resources :orders do
    collection do
      post 'capture_order_paypal'
    end
  end

  resources :webhooks, only: :create


  get ".well-known/apple-developer-merchantid-domain-association" => "payments#apple_domain"

end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id             :bigint           not null, primary key
#  name           :string
#  price_cents    :integer          default(0), not null
#  price_currency :string           default("USD"), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Product < ActiveRecord::Base
  monetize :price_cents
  has_many :orders
end

app/controllers/products/payments_controller.rb
# frozen_string_literal: true

module Products
  class PaymentsController < ApplicationController
    helper_method :product

    def new
      product
    end

    def order_intent
      currency = product.price_currency.downcase
      price_cents = product.price_cents

      order = Order.create!(status: :pending, product:, price_cents:, payment_gateway: :stripe, user: current_user)
      intent_result = Stripe::PaymentIntent.create({
                                                     amount: price_cents,
                                                     currency:,
                                                     automatic_payment_methods: { enabled: true }
                                                   })

      order.charge_id = intent_result.id
      order.token = intent_result.client_secret
      order.save!
      render json: order, status: :created
    end

    def order_paypal
      currency = product.price_currency
      price = product.price.to_s


      result_order = PayPal::Orders::Create.call(total: price,
                                                 currency_code: currency,
                                                 items: [{ name: product.name, value: price }])

      order = Order.create!(status: :pending, product:, price_cents: product.price_cents, payment_gateway: :paypal, user: current_user)
      order.charge_id = result_order.result.id
      order.save!
      render json: result_order.result.table, status: :created
    end

    private

    def product
      product_id = params[:product_id]
      @product ||= Product.find(product_id)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy!
    redirect_to products_url, notice: 'Product was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    # params.fetch(:product, {})
    params.require(:product).permit(:name, :price_cents)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :price_cents %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div class="flex product">
    <span>ID: <%= product.id %></span>
    <div>Name: <%= product.name %></div>
    <div>Price: <%= product.price_cents %></div>
  </div>

</div>

<style>
  .flex{
      display: flex;
  }
  .product{
      width: fit-content;
      margin: 10px 0px;
      padding: 5px;
      flex-direction: column;
      border-left: 6px solid #ccc;
      border-color: #2196F3;
      background: #ddffff;
  }
</style>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show product #{product.name}", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
  <%= button_to "Destroy this product", @product, method: :delete %>
</div>